const books = [
  {"title": "Proofs from THE BOOK",
    "authors": [ "Martin Aigner", "Günter M. Ziegler" ],
    "publisher": "Springer Science & Business Media",
    "published": "2010-01-08",
    "description": "PaulErdos ? likedtotalkaboutTheBook,inwhichGodmaintainstheperfect proofsformathematicaltheorems,followingthedictumofG. H. Hardythat there is no permanent place for ugly mathematics. Erdos ? also said that you need not believe in God but, as a mathematician, you should believe in The Book. A few years ago, we suggested to him to write up a ?rst (and very modest) approximation to The Book. He was enthusiastic about the idea and, characteristically, went to work immediately, ?lling page after page with his suggestions. Our book was supposed to appear in March 1998 as a present to Erdos ? ’ 85th birthday. With Paul’s unfortunate death in the summer of 1996, he is not listed as a co-author. Instead this book is dedicated to his memory. ? Paul Erdos We have no de?nition or characterization of what constitutes a proof from The Book: all we offer here is the examples that we have selected, h- ing that our readers will share our enthusiasm about brilliant ideas, clever insights and wonderful observations. We also hope that our readers will enjoy this despite the imperfections of our exposition. The selection is to a ? great extent in?uencedby Paul Erdos himself. A largenumberof the topics were suggested by him, and many of the proofs trace directly back to him, or were initiated by his supreme insight in asking the right question or in makingthe rightconjecture. So to a largeextentthisbookre?ectstheviews of Paul Erdos ? as to what should be considered a proof from The Book.",
    "pageCount": 274,
    "printType": "BOOK",
    "genres": [ "Mathematics" ],
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "tj_hr2CGXFwC",
    "link": "http://books.google.com/books/about/Proofs_from_THE_BOOK.html?hl=&id=tj_hr2CGXFwC",
    "thumbnail": "http://books.google.com/books/content?id=tj_hr2CGXFwC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Book Thief",
    "authors": [ "Markus Zusak" ],
    "publisher": "Knopf Books for Young Readers",
    "published": "2007-12-18",
    "description": "The extraordinary #1 New York Times bestseller that is now a major motion picture, Markus Zusak\"s unforgettable story is about the ability of books to feed the soul. It is 1939. Nazi Germany. The country is holding its breath. Death has never been busier, and will become busier still. Liesel Meminger is a foster girl living outside of Munich, who scratches out a meager existence for herself by stealing when she encounters something she can’t resist–books. With the help of her accordion-playing foster father, she learns to read and shares her stolen books with her neighbors during bombing raids as well as with the Jewish man hidden in her basement. In superbly crafted writing that burns with intensity, award-winning author Markus Zusak, author of I Am the Messenger, has given us one of the most enduring stories of our time.",
    "pageCount": 592,
    "printType": "BOOK",
    "genres": [ "Young Adult Fiction" ],
    "averageRating": 4.5,
    "ratingsCount": 3445,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "veGXULZK6UAC",
    "link": "http://books.google.com/books/about/The_Book_Thief.html?hl=&id=veGXULZK6UAC",
    "thumbnail": "http://books.google.com/books/content?id=veGXULZK6UAC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  { "title": "The Book of Mormon",
    "subtitle": "Compared with the Original Manuscript and the Kirtland Edition of 1837, which was Carefully Re-examined and Compared with the Original Manuscript by Joseph Smith and Oliver Cowdery",
    "authors": [ "Joseph Smith (Jr.)", "Community of Christ" ],
    "published": "2002",
    "pageCount": 387,
    "printType": "BOOK",
    "genres": [ "Church of Jesus Christ Latter-day Saints" ],
    "averageRating": 5,
    "ratingsCount": 4,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "E90dMwEACAAJ",
    "link": "http://books.google.com/books/about/The_Book_of_Mormon.html?hl=&id=E90dMwEACAAJ",
    "thumbnail": "",
    "images": {} },
  {"title": "Trump: The Art of the Deal",
    "authors": [ "Donald J. Trump", "Tony Schwartz" ],
    "publisher": "Ballantine Books",
    "published": "2009-12-23",
    "description": "Presumptive Republican presidential nominee Donald J. Trump lays out his professional and personal worldview in this classic work—a firsthand account of the rise of America’s foremost deal-maker. “I like thinking big. I always have. To me it’s very simple: If you’re going to be thinking anyway, you might as well think big.”—Donald J. Trump Here is Trump in action—how he runs his organization and how he runs his life—as he meets the people he needs to meet, chats with family and friends, clashes with enemies, and challenges conventional thinking. But even a maverick plays by rules, and Trump has formulated time-tested guidelines for success. He isolates the common elements in his greatest accomplishments; he shatters myths; he names names, spells out the zeros, and fully reveals the deal-maker’s art. And throughout, Trump talks—really talks—about how he does it. Trump: The Art of the Deal is an unguarded look at the mind of a brilliant entrepreneur—the ultimate read for anyone interested in the man behind the spotlight. Praise for Trump: The Art of the Deal “Trump makes one believe for a moment in the American dream again.”—The New York Times “Donald Trump is a deal maker. He is a deal maker the way lions are carnivores and water is wet.”—Chicago Tribune “Fascinating . . . wholly absorbing . . . conveys Trump’s larger-than-life demeanor so vibrantly that the reader’s attention is instantly and fully claimed.”—Boston Herald “A chatty, generous, chutzpa-filled autobiography.”—New York Post From the Hardcover edition.",
    "pageCount": 384,
    "printType": "BOOK",
    "genres": [ "Business & Economics" ],
    "averageRating": 3.5,
    "ratingsCount": 12,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "Ye6e_VxM00kC",
    "link": "http://books.google.com/books/about/Trump_The_Art_of_the_Deal.html?hl=&id=Ye6e_VxM00kC",
    "thumbnail": "http://books.google.com/books/content?id=Ye6e_VxM00kC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Book of Woe",
    "subtitle": "The DSM and the Unmaking of Psychiatry",
    "authors": [ "Gary Greenberg" ],
    "publisher": "Penguin",
    "published": "2013-05-02",
    "description": "“Gary Greenberg has become the Dante of our psychiatric age, and the DSM-5 is his Inferno.” —Errol Morris Since its debut in 1952, the American Psychiatric Association’s Diagnostic and Statistical Manual of Mental Disorders has set down the “official” view on what constitutes mental illness. Homosexuality, for instance, was a mental illness until 1973. Each revision has created controversy, but the DSM-5 has taken fire for encouraging doctors to diagnose more illnesses—and to prescribe sometimes unnecessary or harmful medications. Respected author and practicing psychotherapist Gary Greenberg embedded himself in the war that broke out over the fifth edition, and returned with an unsettling tale. Exposing the deeply flawed process behind the DSM-5’s compilation, The Book of Woe reveals how the manual turns suffering into a commodity—and made the APA its own biggest beneficiary.",
    "pageCount": 416,
    "printType": "BOOK",
    "genres": [ "Psychology" ],
    "averageRating": 3.5,
    "ratingsCount": 2,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "H3DhV3syneMC",
    "link": "http://books.google.com/books/about/The_Book_of_Woe.html?hl=&id=H3DhV3syneMC",
    "thumbnail": "http://books.google.com/books/content?id=H3DhV3syneMC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Lean Startup",
    "subtitle": "How Today\"s Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses",
    "authors": [ "Eric Ries" ],
    "publisher": "Crown Business",
    "published": "2011-09-13",
    "description": "Most startups fail. But many of those failures are preventable. The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched. Eric Ries defines a startup as an organization dedicated to creating something new under conditions of extreme uncertainty. This is just as true for one person in a garage or a group of seasoned professionals in a Fortune 500 boardroom. What they have in common is a mission to penetrate that fog of uncertainty to discover a successful path to a sustainable business. The Lean Startup approach fosters companies that are both more capital efficient and that leverage human creativity more effectively. Inspired by lessons from lean manufacturing, it relies on “validated learning,” rapid scientific experimentation, as well as a number of counter-intuitive practices that shorten product development cycles, measure actual progress without resorting to vanity metrics, and learn what customers really want. It enables a company to shift directions with agility, altering plans inch by inch, minute by minute. Rather than wasting time creating elaborate business plans, The Lean Startup offers entrepreneurs - in companies of all sizes - a way to test their vision continuously, to adapt and adjust before it’s too late. Ries provides a scientific approach to creating and managing successful startups in a age when companies need to innovate more than ever. From the Hardcover edition.",
    "pageCount": 336,
    "printType": "BOOK",
    "genres": [ "Business & Economics" ],
    "averageRating": 4,
    "ratingsCount": 2136,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "tvfyz-4JILwC",
    "link": "http://books.google.com/books/about/The_Lean_Startup.html?hl=&id=tvfyz-4JILwC",
    "thumbnail": "http://books.google.com/books/content?id=tvfyz-4JILwC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "Moneyball: The Art of Winning an Unfair Game",
    "authors": [ "Michael Lewis" ],
    "publisher": "W. W. Norton & Company",
    "published": "2004-03-17",
    "description": "\"This delightfully written, lesson-laden book deserves a place of its own in the Baseball Hall of Fame.\" —Forbes Moneyball is a quest for the secret of success in baseball. In a narrative full of fabulous characters and brilliant excursions into the unexpected, Michael Lewis follows the low-budget Oakland A\"s, visionary general manager Billy Beane, and the strange brotherhood of amateur baseball theorists. They are all in search of new baseball knowledge—insights that will give the little guy who is willing to discard old wisdom the edge over big money.",
    "pageCount": 320,
    "printType": "BOOK",
    "genres": [ "Sports & Recreation" ],
    "averageRating": 4,
    "ratingsCount": 81,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "oIYNBodW-ZEC",
    "link": "http://books.google.com/books/about/Moneyball_The_Art_of_Winning_an_Unfair_G.html?hl=&id=oIYNBodW-ZEC",
    "thumbnail": "http://books.google.com/books/content?id=oIYNBodW-ZEC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The English East India Company",
    "subtitle": "The Study of an Early Joint-stock Company 1600-1640",
    "authors": [ "K. N. Chaudhuri" ],
    "publisher": "Taylor & Francis",
    "published": "1965",
    "description": "First published in 1999. Routledge is an imprint of Taylor & Francis, an informa company.",
    "pageCount": 245,
    "printType": "BOOK",
    "genres": [ "Business & Economics" ],
    "averageRating": 5,
    "ratingsCount": 1,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "Dyn3oh06ue8C",
    "link": "http://books.google.com/books/about/The_English_East_India_Company.html?hl=&id=Dyn3oh06ue8C",
    "thumbnail": "http://books.google.com/books/content?id=Dyn3oh06ue8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Manual of Museum Exhibitions",
    "authors": [ "Barry Lord", "Gail Dexter Lord" ],
    "publisher": "Rowman Altamira",
    "published": "2002",
    "description": "This is a guide to the process of planning, designing, producing and evaluating exhibitions for museums. Subjects range from traditional displays of art, artifacts and specimens from the permanent collection to the latest developments in virtual reality, online exhibitions, and big-screen reality.",
    "pageCount": 544,
    "printType": "BOOK",
    "genres": [ "Business & Economics" ],
    "averageRating": 5,
    "ratingsCount": 4,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "dTKb1kk88McC",
    "link": "http://books.google.com/books/about/The_Manual_of_Museum_Exhibitions.html?hl=&id=dTKb1kk88McC",
    "thumbnail": "http://books.google.com/books/content?id=dTKb1kk88McC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The American Disease",
    "subtitle": "Origins of Narcotic Control",
    "authors": [ "David F. Musto" ],
    "publisher": "Oxford University Press",
    "published": "1999-04-22",
    "description": "The American Disease is a classic study of the development of drug laws in the United States. Supporting the theory that Americans\" attitudes toward drugs have followed a cyclic pattern of tolerance and restraint, author David F. Musto examines the relationz between public outcry and the creation of prohibitive drug laws from the end of the Civil War up to the present. Originally published in 1973, and then in an expanded edition in 1987, this third edition contains a new chapter and preface that both address the renewed debate on policy and drug legislation from the end of the Reagan administration to the current Clinton administration. Here, Musto thoroughly investigates how our nation has dealt with such issues as the controversies over prevention programs and mandatory minimum sentencing, the catastrophe of the crack epidemic, the fear of a heroin revival, and the continued debate over the legalization of marijuana.",
    "pageCount": 432,
    "printType": "BOOK",
    "genres": [ "Psychology" ],
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "7VrQy2d8PxYC",
    "link": "http://books.google.com/books/about/The_American_Disease.html?hl=&id=7VrQy2d8PxYC",
    "thumbnail": "http://books.google.com/books/content?id=7VrQy2d8PxYC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Psychology of Interpersonal Relations",
    "authors": [ "Fritz Heider" ],
    "publisher": "Psychology Press",
    "published": "1958",
    "description": "As the title suggests, this book examines the psychology of interpersonal relations. In the context of this book, the term \"interpersonal relations\" denotes relations between a few, usually between two, people. How one person thinks and feels about another person, how he perceives him and what he does to him, what he expects him to do or think, how he reacts to the actions of the other--these are some of the phenomena that will be treated. Our concern will be with \"surface\" matters, the events that occur in everyday life on a conscious level, rather than with the unconscious processes studied by psychoanalysis in \"depth\" psychology. These intuitively understood and \"obvious\" human relations can, as we shall see, be just as challenging and psychologically significant as the deeper and stranger phenomena. The discussion will center on the person as the basic unit to be investigated. That is to say, the two-person group and its properties as a superindividual unit will not be the focus of attention. Of course, in dealing with the person as a member of a dyad, he cannot be described as a lone subject in an impersonal environment, but must be represented as standing in relation to and interacting with another person. The chapter topics included in this book include: Perceiving the Other Person; The Other Person as Perceiver; The Naive Analysis of Action; Desire and Pleasure; Environmental Effects; Sentiment; Ought and Value; Request and Command; Benefit and Harm; and Reaction to the Lot of the Other Person.",
    "pageCount": 322,
    "printType": "BOOK",
    "genres": [ "Psychology" ],
    "averageRating": 3.5,
    "ratingsCount": 2,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "Zh6TDmayL0AC",
    "link": "http://books.google.com/books/about/The_Psychology_of_Interpersonal_Relation.html?hl=&id=Zh6TDmayL0AC",
    "thumbnail": "http://books.google.com/books/content?id=Zh6TDmayL0AC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Book of Aron",
    "subtitle": "A novel",
    "authors": [ "Jim Shepard" ],
    "publisher": "Vintage",
    "published": "2015-05-12",
    "description": "The acclaimed National Book Award finalist—“one of the United States’ finest writers,” according to Joshua Ferris, “full of wit, humanity, and fearless curiosity”—now gives us a novel that will join the short list of classics about children caught up in the Holocaust. Aron, the narrator, is an engaging if peculiar and unhappy young boy whose family is driven by the German onslaught from the Polish countryside into Warsaw and slowly battered by deprivation, disease, and persecution. He and a handful of boys and girls risk their lives by scuttling around the ghetto to smuggle and trade contraband through the quarantine walls in hopes of keeping their fathers, mothers, brothers, and sisters alive, hunted all the while by blackmailers and by Jewish, Polish, and German police, not to mention the Gestapo. When his family is finally stripped away from him, Aron is rescued by Janusz Korczak, a doctor renowned throughout prewar Europe as an advocate of children’s rights who, once the Nazis swept in, was put in charge of the Warsaw orphanage. Treblinka awaits them all, but does Aron manage to escape—as his mentor suspected he could—to spread word about the atrocities? Jim Shepard has masterfully made this child’s-eye view of the darkest history mesmerizing, sometimes comic despite all odds, truly heartbreaking, and even inspiring. Anyone who hears Aron’s voice will remember it forever. From the Hardcover edition.",
    "pageCount": 272,
    "printType": "BOOK",
    "genres": [ "Fiction" ],
    "averageRating": 3,
    "ratingsCount": 3,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "FZNoBAAAQBAJ",
    "link": "http://books.google.com/books/about/The_Book_of_Aron.html?hl=&id=FZNoBAAAQBAJ",
    "thumbnail": "http://books.google.com/books/content?id=FZNoBAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Modern Invention of Medieval Music",
    "subtitle": "Scholarship, Ideology, Performance",
    "authors": [ "Daniel Leech-Wilkinson" ],
    "publisher": "Cambridge University Press",
    "published": "2002-10-17",
    "description": "A challenging book which questions how much is really known about the way medieval music sounded.",
    "pageCount": 335,
    "printType": "BOOK",
    "genres": [ "History" ],
    "averageRating": 3,
    "ratingsCount": 2,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "GRrJ6zmxvPcC",
    "link": "http://books.google.com/books/about/The_Modern_Invention_of_Medieval_Music.html?hl=&id=GRrJ6zmxvPcC",
    "thumbnail": "http://books.google.com/books/content?id=GRrJ6zmxvPcC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "Slave Culture : Nationalist Theory and the Foundations of Black America",
    "subtitle": "Nationalist Theory and the Foundations of Black America",
    "authors": [ "Sterling Stuckey Professor of History Northwestern University" ],
    "publisher": "Oxford University Press, USA",
    "published": "1987-04-23",
    "description": "How were blacks in American slavery formed, out of a multiplicity of African ethnic peoples, into a single people? In this major study of Afro-American culture, Sterling Stuckey, a leading thinker on black nationalism for the past twenty years, explains how different African peoples interacted during the nineteenth century to achieve a common culture. He finds that, at the time of emancipation, slaves were still overwhelmingly African in culture, a conclusion with profound implications for theories of black liberation and for the future of race relations in America. By examining anthropological evidence about Central and West African cultural traditions--Bakongo, Ibo, Dahomean, Mendi and others--and exploring the folklore of the American slave, Stuckey has arrived at an important new cross-cultural analysis of the Pan-African impulse among slaves that contributed to the formation of a black ethos. He establishes, for example, the centrality of an ancient African ritual--the Ring Shout or Circle Dance--to the black American religious and artistic experience. Black nationalist theories, the author points out, are those most in tune with the implication of an African presence in America during and since slavery. Casting a fresh new light on these ideas, Stuckey provides us with fascinating profiles of such nineteenth century figures as David Walker, Henry Highland Garnet, and Frederick Douglas. He then considers in detail the lives and careers of W. E. B. Dubois and Paul Robeson in this century, describing their ambition that blacks in American society, while struggling to end racism, take on roles that truly reflected their African heritage. These concepts of black liberation, Stuckey suggests, are far more relevant to the intrinsic values of black people than integrationist thought on race relations. But in a final revelation he concludes that, with the exception of Paul Robeson, the ironic tendency of black nationalists has been to underestimate the depths of African culture in black Americans and the sophistication of the slave community they arose from.",
    "pageCount": 444,
    "printType": "BOOK",
    "genres": [ "History" ],
    "averageRating": 2,
    "ratingsCount": 1,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "EysCsWG7OdYC",
    "link": "http://books.google.com/books/about/Slave_Culture_Nationalist_Theory_and_the.html?hl=&id=EysCsWG7OdYC",
    "thumbnail": "http://books.google.com/books/content?id=EysCsWG7OdYC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The 5th Wave",
    "authors": [ "Rick Yancey" ],
    "publisher": "Penguin",
    "published": "2013-05-07",
    "description": "Remarkable, not-to-be-missed-under-any-circumstances.\"—Entertainment Weekly (Grade A) The Passage meets Ender\"s Game in an epic new series from award-winning author Rick Yancey. After the 1st wave, only darkness remains. After the 2nd, only the lucky escape. And after the 3rd, only the unlucky survive. After the 4th wave, only one rule applies: trust no one. Now, it\"s the dawn of the 5th wave, and on a lonely stretch of highway, Cassie runs from Them. The beings who only look human, who roam the countryside killing anyone they see. Who have scattered Earth\"s last survivors. To stay alone is to stay alive, Cassie believes, until she meets Evan Walker. Beguiling and mysterious, Evan Walker may be Cassie\"s only hope for rescuing her brother--or even saving herself. But Cassie must choose: between trust and despair, between defiance and surrender, between life and death. To give up or to get up. \"Wildly entertaining . . . I couldn\"t turn the pages fast enough.\"—Justin Cronin, The New York Times Book Review \"A modern sci-fi masterpiece . . . should do for aliens what Twilight did for vampires.\"—USAToday.com\"",
    "pageCount": 480,
    "printType": "BOOK",
    "genres": [ "Young Adult Fiction" ],
    "averageRating": 4,
    "ratingsCount": 2224,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "QHg_-SrbNGEC",
    "link": "http://books.google.com/books/about/The_5th_Wave.html?hl=&id=QHg_-SrbNGEC",
    "thumbnail": "http://books.google.com/books/content?id=QHg_-SrbNGEC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "Style in the Technical and Tectonic Arts, Or, Practical Aesthetics",
    "authors":
     [ "Gottfried Semper",
       "Harry Francis Mallgrave",
       "Michael Robinson",
       "Getty Research Institute" ],
    "publisher": "Getty Publications",
    "published": "2004",
    "description": "The enduring influence of the architect Gottfried Semper (1803-1879) derives primarily from his monumental theoretical foray Der Stil in der technischen und tektonischen Kunsten (1860-62), here translated into English for the first time. A richly illustrated survey of the technical arts (textiles, ceramics, carpentry, masonry), Semper\"s analysis of the preconditions of style forever changed the interpretative context for aesthetics, architecture, and art history. Style, Semper believed, should be governed by historical function, cultural affinities, creative free will, and the innate properties of each medium. Thus, in an ambitious attempt to turn nineteenth-century artistic discussion away from historicism, aestheticism, and materialism, Semper developed in Der Stil a complex picture of stylistic change based on scrutiny of specific objects and a remarkable grasp of cultural variety. Harry Francis Mallgrave\"s introductory essay offers an account of Semper\"s life and work, a survey of Der Stil, and a fresh consideration of Semper\"s landmark study and its lasting significance.",
    "pageCount": 980,
    "printType": "BOOK",
    "genres": [ "Art" ],
    "averageRating": 5,
    "ratingsCount": 1,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "5mCcKu6HhMAC",
    "link": "http://books.google.com/books/about/Style_in_the_Technical_and_Tectonic_Arts.html?hl=&id=5mCcKu6HhMAC",
    "thumbnail": "http://books.google.com/books/content?id=5mCcKu6HhMAC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Natural History of Pliny",
    "authors": [ "Pliny (the Elder.)" ],
    "published": "1855",
    "printType": "BOOK",
    "genres": [ "Natural history" ],
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "A0EMAAAAIAAJ",
    "link": "http://books.google.com/books/about/The_Natural_History_of_Pliny.html?hl=&id=A0EMAAAAIAAJ",
    "thumbnail": "http://books.google.com/books/content?id=A0EMAAAAIAAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Anointed Community",
    "subtitle": "The Holy Spirit in the Johannine Tradition",
    "authors": [ "Gary M. Burge" ],
    "publisher": "Wm. B. Eerdmans Publishing",
    "published": "1987",
    "description": "Recent research on the Johannine literature has concluded that behind these writings stands a flourishing community of Christians who lived under the tutelage of the Beloved Disciple, preserved his writings, and venerated his memory. In this book, Gary M. Burge examines one feature of this community\"s belief and experience: the role of the Spirit in its view both of Christ and of the Christian experience.",
    "pageCount": 269,
    "printType": "BOOK",
    "genres": [ "Religion" ],
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "brwOUOLTTFwC",
    "link": "http://books.google.com/books/about/The_Anointed_Community.html?hl=&id=brwOUOLTTFwC",
    "thumbnail": "http://books.google.com/books/content?id=brwOUOLTTFwC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The University in Ruins",
    "authors": [ "Bill Readings" ],
    "publisher": "Harvard University Press",
    "published": "1996",
    "description": "Tracing the roots of the modern American University in German philosophy & in the work of British thinkers such as Newman & Arnold, Readings argues that historically the integrity of the modern university has been linked to the nation-state.",
    "pageCount": 238,
    "printType": "BOOK",
    "genres": [ "Education" ],
    "averageRating": 5,
    "ratingsCount": 1,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "twspbqgF3YIC",
    "link": "http://books.google.com/books/about/The_University_in_Ruins.html?hl=&id=twspbqgF3YIC",
    "thumbnail": "http://books.google.com/books/content?id=twspbqgF3YIC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Fragment",
    "subtitle": "An Incomplete History",
    "authors": [ "William Tronzo" ],
    "publisher": "Getty Publications",
    "published": "2009",
    "description": "A collection of essays on art history and criticism. The essays offer a meditation on distinctive moments in the history of the fragment, ranging from spoila in late antique architecture to the practice of collage in the modern period.",
    "pageCount": 222,
    "printType": "BOOK",
    "genres": [ "Language Arts & Disciplines" ],
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "nhTzJ4fYAnEC",
    "link": "http://books.google.com/books/about/The_Fragment.html?hl=&id=nhTzJ4fYAnEC",
    "thumbnail": "http://books.google.com/books/content?id=nhTzJ4fYAnEC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The High Price of Materialism",
    "authors": [ "Tim Kasser" ],
    "publisher": "MIT Press",
    "published": "2003-08",
    "description": "A study of how materialism and consumerism undermine our quality of life.",
    "pageCount": 149,
    "printType": "BOOK",
    "genres": [ "Philosophy" ],
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "2ekg225NTSwC",
    "link": "http://books.google.com/books/about/The_High_Price_of_Materialism.html?hl=&id=2ekg225NTSwC",
    "thumbnail": "http://books.google.com/books/content?id=2ekg225NTSwC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "Tactics and the Experience of Battle in the Age of Napoleon",
    "authors": [ "Rory Muir" ],
    "publisher": "Yale University Press",
    "published": "2000-02",
    "description": "What was it like to be a soldier on a Napoleonic battlefield? What happened when cavalry regiments charged directly at one another? What did the generals do during battle? Drawing on memoirs, diaries and letters of the time, this book explores what actually happened in battle and how the participants\" feelings and reactions influenced the outcome. Rory Muir focuses on the dynamics of combat in the age of Napoleon, enhancing his analysis with accounts of those who were there - the frightened foot soldier, the general in command, the young cavalry officer whose boils made it impossible to ride, and the smartly dressed aide-de-camp, tripped up by his voluminous pantaloons.",
    "pageCount": 352,
    "printType": "BOOK",
    "genres": [ "History" ],
    "averageRating": 5,
    "ratingsCount": 1,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "_03Pfl3dx7YC",
    "link": "http://books.google.com/books/about/Tactics_and_the_Experience_of_Battle_in.html?hl=&id=_03Pfl3dx7YC",
    "thumbnail": "http://books.google.com/books/content?id=_03Pfl3dx7YC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Hebrew Bible Today",
    "subtitle": "An Introduction to Critical Issues",
    "authors": [ "Steven L. McKenzie", "Matt Patrick Graham" ],
    "publisher": "Westminster John Knox Press",
    "published": "1998-01-01",
    "description": "Dealing with each section of the canon, this book explains standard questions, paying special attention to where scholars agree and where they don\"t.",
    "pageCount": 240,
    "printType": "BOOK",
    "genres": [ "Religion" ],
    "averageRating": 4,
    "ratingsCount": 1,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "owwhpmIVgSAC",
    "link": "http://books.google.com/books/about/The_Hebrew_Bible_Today.html?hl=&id=owwhpmIVgSAC",
    "thumbnail": "http://books.google.com/books/content?id=owwhpmIVgSAC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Gutenberg Galaxy",
    "subtitle": "The Making of Typographic Man",
    "authors": [ "Marshall McLuhan" ],
    "publisher": "University of Toronto Press",
    "published": "1962",
    "description": "A history of western society and print technology from a media perspective.",
    "pageCount": 293,
    "printType": "BOOK",
    "genres": [ "Social Science" ],
    "averageRating": 4,
    "ratingsCount": 6,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "y4C644zHCWgC",
    "link": "http://books.google.com/books/about/The_Gutenberg_Galaxy.html?hl=&id=y4C644zHCWgC",
    "thumbnail": "http://books.google.com/books/content?id=y4C644zHCWgC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Sino-Tibetan Languages",
    "authors": [ "Graham Thurgood", "Randy J. LaPolla" ],
    "publisher": "Psychology Press",
    "published": "2003",
    "description": "There are more native speakers of Sino-Tibetan languages than of any other language family in the world. Records of these languages are among the oldest for any human language, and the amount of active research on them, both diachronic and synchronic, has multiplied in the last few decades. This volume includes overview articles as well as descriptions of individual languages and comments on the subgroups in which they occur. In addition to a number of modern languages, there are descriptions of several ancient languages.",
    "pageCount": 727,
    "printType": "BOOK",
    "genres": [ "Foreign Language Study" ],
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "5MeWSTQ7F44C",
    "link": "http://books.google.com/books/about/The_Sino_Tibetan_Languages.html?hl=&id=5MeWSTQ7F44C",
    "thumbnail": "http://books.google.com/books/content?id=5MeWSTQ7F44C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "For the City Yet to Come",
    "subtitle": "Changing African Life in Four Cities",
    "authors": [ "AbdouMaliq Simone" ],
    "publisher": "Duke University Press",
    "published": "2004-09-16",
    "description": "Among government officials, urban planners, and development workers, Africa’s burgeoning metropolises are frequently understood as failed cities, unable to provide even basic services. Whatever resourcefulness does exist is regarded as only temporary compensation for fundamental failure. In For the City Yet to Come, AbdouMaliq Simone argues that by overlooking all that does work in Africa’s cities, this perspective forecloses opportunities to capitalize on existing informal economies and structures in development efforts within Africa and to apply lessons drawn from them to rapidly growing urban areas around the world. Simone contends that Africa’s cities do work on some level and to the extent that they do, they function largely through fluid, makeshift collective actions running parallel to proliferating decentralized local authorities, small-scale enterprises, and community associations. Drawing on his nearly fifteen years of work in African cities—as an activist, teacher, development worker, researcher, and advisor to ngos and local governments—Simone provides a series of case studies illuminating the provisional networks through which most of Africa’s urban dwellers procure basic goods and services. He examines informal economies and social networks in Pikine, a large suburb of Dakar, Senegal; in Winterveld, a neighborhood on the edge of Pretoria, South Africa; in Douala, Cameroon; and among Africans seeking work in Jeddah, Saudi Arabia. He contextualizes these particular cases through an analysis of the broad social, economic, and historical conditions that created present-day urban Africa. For the City Yet to Come is a powerful argument that any serious attempt to reinvent African urban centers must acknowledge the particular history of these cities and incorporate the local knowledge reflected in already existing informal urban economic and social systems.",
    "pageCount": 297,
    "printType": "BOOK",
    "genres": [ "Social Science" ],
    "averageRating": 4,
    "ratingsCount": 1,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "KeGdSs6dFioC",
    "link": "http://books.google.com/books/about/For_the_City_Yet_to_Come.html?hl=&id=KeGdSs6dFioC",
    "thumbnail": "http://books.google.com/books/content?id=KeGdSs6dFioC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "Reflections of the Rav",
    "subtitle": "Lessons in Jewish Thought Adapted from the Lectures of Rabbi Joseph B. Soloveitchik",
    "authors": [ "Abraham R. Besdin" ],
    "publisher": "KTAV Publishing House, Inc.",
    "published": "1993-01-01",
    "description": "Rabbi Besdin\"s first volume of \"reconstructions\" of the thought of \"the Rav,\" Rabbi J.B. Soloveitchik, revered halakhic and spiritual mentor of centrist Orthodoxy, was widely acclaimed when first published and continues to be reprinted.",
    "printType": "BOOK",
    "genres": [ "Religion" ],
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "75WlJgOlHfgC",
    "link": "http://books.google.com/books/about/Reflections_of_the_Rav.html?hl=&id=75WlJgOlHfgC",
    "thumbnail": "http://books.google.com/books/content?id=75WlJgOlHfgC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Cambridge Guide to Women\"s Writing in English",
    "authors": [ "Lorna Sage", "Germaine Greer", "Elaine Showalter" ],
    "publisher": "Cambridge University Press",
    "published": "1999-09-30",
    "description": "Alphabetized volume on women writers, major titles, movements, genres from medieval times to the present.",
    "pageCount": 696,
    "printType": "BOOK",
    "genres": [ "Literary Criticism" ],
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "NB59uc9_ss8C",
    "link": "http://books.google.com/books/about/The_Cambridge_Guide_to_Women_s_Writing_i.html?hl=&id=NB59uc9_ss8C",
    "thumbnail": "http://books.google.com/books/content?id=NB59uc9_ss8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The American Revolution",
    "authors": [ "Colin Bonwick" ],
    "publisher": "University of Virginia Press",
    "published": "1991",
    "description": "This book traces the development of the United States from the 1760s to the consolidation of the federal government during the 1790s. The author argues that the creation of the American republic was a major revolution; by the time it was complete the United States was radically different from Britain and the colonies out which it had emerged. Extensive coverage is given to the establishment of governments, first in the states then at the national level, and to social development in the states. It is argued that many of of the most significant changes took place at this level.",
    "pageCount": 336,
    "printType": "BOOK",
    "genres": [ "History" ],
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "B8tKlNRnc_wC",
    "link": "http://books.google.com/books/about/The_American_Revolution.html?hl=&id=B8tKlNRnc_wC",
    "thumbnail": "http://books.google.com/books/content?id=B8tKlNRnc_wC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Book of Unknown Americans",
    "subtitle": "A novel",
    "authors": [ "Cristina Henr??quez" ],
    "publisher": "Vintage",
    "published": "2014-06-03",
    "description": "“A triumph of storytelling. Henríquez pulls us into the lives of her characters with such mastery that we hang on to them just as fiercely as they hang on to one another and their dreams. This passionate, powerful novel will stay with you long after you’ve turned the final page.” —Ben Fountain, author of Billy Lynn’s Long Halftime Walk A boy and a girl who fall in love. Two families whose hopes collide with destiny. An extraordinary novel that offers a resonant new definition of what it means to be American. Arturo and Alma Rivera have lived their whole lives in Mexico. One day, their beautiful fifteen-year-old daughter, Maribel, sustains a terrible injury, one that casts doubt on whether she’ll ever be the same. And so, leaving all they have behind, the Riveras come to America with a single dream: that in this country of great opportunity and resources, Maribel can get better. When Mayor Toro, whose family is from Panama, sees Maribel in a Dollar Tree store, it is love at first sight. It’s also the beginning of a friendship between the Rivera and Toro families, whose web of guilt and love and responsibility is at this novel’s core. Woven into their stories are the testimonials of men and women who have come to the United States from all over Latin America. Their journeys and their voices will inspire you, surprise you, and break your heart. Suspenseful, wry and immediate, rich in spirit and humanity, The Book of Unknown Americans is a work of rare force and originality. This eBook edition includes a Reading Group Guide.",
    "pageCount": 304,
    "printType": "BOOK",
    "genres": [ "Fiction" ],
    "averageRating": 4,
    "ratingsCount": 10,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "jixPAgAAQBAJ",
    "link": "http://books.google.com/books/about/The_Book_of_Unknown_Americans.html?hl=&id=jixPAgAAQBAJ",
    "thumbnail": "http://books.google.com/books/content?id=jixPAgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Nature of the Book",
    "subtitle": "Print and Knowledge in the Making",
    "authors": [ "Adrian Johns" ],
    "publisher": "University of Chicago Press",
    "published": "1998-01",
    "description": "Discusses how books were written, printed, and distributed in early modern England; the relationships among authors, printers, booksellers, and government officials; and the impact of technological innovation.",
    "pageCount": 753,
    "printType": "BOOK",
    "genres": [ "Language Arts & Disciplines" ],
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "zobsj8npWeAC",
    "link": "http://books.google.com/books/about/The_Nature_of_the_Book.html?hl=&id=zobsj8npWeAC",
    "thumbnail": "http://books.google.com/books/content?id=zobsj8npWeAC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "Pushing to the Front",
    "authors": [ "Orison Swett Marden" ],
    "published": "1911",
    "pageCount": 824,
    "printType": "BOOK",
    "genres": [ "Success" ],
    "averageRating": 5,
    "ratingsCount": 2,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "O08XASG_cgYC",
    "link": "http://books.google.com/books/about/Pushing_to_the_Front.html?hl=&id=O08XASG_cgYC",
    "thumbnail": "http://books.google.com/books/content?id=O08XASG_cgYC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "Keats the Poet",
    "authors": [ "Stuart M. Sperry" ],
    "publisher": "Princeton University Press",
    "published": "1973",
    "description": "Keats the Poet was first published in 1973, just as the crest of all the New-Critical exegeses had passed, leaving the critical literature with a wealth of fine readings, but without a real organizing program within which to view them. Stuart Sperry established such a frame of reference. Further, he did so with such prescience that even the most radical deconstructive or new historical approaches to Keats today must bear witness to their inception in Sperry\"s emphasis on, and subtle demonstration of, the centrality of \"indeterminacy\" in the poet. Now available in paperback for the first time, this work will enlighten a new generation of readers.",
    "pageCount": 354,
    "printType": "BOOK",
    "genres": [ "Literary Criticism" ],
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "T6padd5rVZkC",
    "link": "http://books.google.com/books/about/Keats_the_Poet.html?hl=&id=T6padd5rVZkC",
    "thumbnail": "http://books.google.com/books/content?id=T6padd5rVZkC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The New Hacker\"s Dictionary",
    "authors": [ "Eric S. Raymond" ],
    "publisher": "MIT Press",
    "published": "1996",
    "description": "A listing of computer-buff slang is embellished by the myths, legends, and heroes of a hacker culture",
    "pageCount": 547,
    "printType": "BOOK",
    "genres": [ "Computers" ],
    "averageRating": 4.5,
    "ratingsCount": 3,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "g80P_4v4QbIC",
    "link": "http://books.google.com/books/about/The_New_Hacker_s_Dictionary.html?hl=&id=g80P_4v4QbIC",
    "thumbnail": "http://books.google.com/books/content?id=g80P_4v4QbIC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The crisis",
    "subtitle": "or, Essays on the usurpations of the federal government",
    "authors": [ "Robert James Turnbull", "Brutus (pseud.)" ],
    "published": "1827",
    "pageCount": 166,
    "printType": "BOOK",
    "genres": [ "State rights" ],
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "uofICHdr0zsC",
    "link": "http://books.google.com/books/about/The_crisis.html?hl=&id=uofICHdr0zsC",
    "thumbnail": "http://books.google.com/books/content?id=uofICHdr0zsC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Park and the People",
    "subtitle": "A History of Central Park",
    "authors": [ "Roy Rosenzweig", "Elizabeth Blackmar" ],
    "publisher": "Cornell University Press",
    "published": "1992",
    "description": "Delineate the politicians, business people, artists, immigrant laborers, and city dwellers who are the key players in the tale. In tracing the park\"s history, the writers also give us the history of New York. They explain how squabbles over politics, taxes, and real estate development shaped the park and describe the acrimonious debates over what a public park should look like, what facilities it should offer, and how it should accommodate the often incompatible.",
    "pageCount": 623,
    "printType": "BOOK",
    "genres": [ "History" ],
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "sp93FnkRKiIC",
    "link": "http://books.google.com/books/about/The_Park_and_the_People.html?hl=&id=sp93FnkRKiIC",
    "thumbnail": "http://books.google.com/books/content?id=sp93FnkRKiIC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Death of Tragedy",
    "authors": [ "George Steiner" ],
    "publisher": "Yale University Press",
    "published": "1996",
    "description": "This is a brilliantly thoughtful and eloquent book which deserves to be read with the greatest attention and respect. It covers an enormous subject, and is almost a survey of the whole history of tragedy from the Greeks to Samuel Beckett.",
    "pageCount": 368,
    "printType": "BOOK",
    "genres": [ "Literary Criticism" ],
    "averageRating": 4.5,
    "ratingsCount": 2,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "ZA3_bYqHOegC",
    "link": "http://books.google.com/books/about/The_Death_of_Tragedy.html?hl=&id=ZA3_bYqHOegC",
    "thumbnail": "http://books.google.com/books/content?id=ZA3_bYqHOegC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Faith of the Christian Church",
    "subtitle": "An Introduction to Theology",
    "authors": [ "Tyron Inbody" ],
    "publisher": "Wm. B. Eerdmans Publishing",
    "published": "2005-04-14",
    "description": "Tyron Inbody has taught the basics of Christian theology for more than twenty-five years. Having seen over the years what issues and questions his students bring to class, he now offers this engaging, accessible introduction to all the major beliefs of the Christian faith. Meant especially but not exclusively for readers new to theology, Inbody\"s Faith of the Christian Church covers twelve traditional areas of Christian teaching: theology, revelation, faith, God, creation, suffering and evil, humankind, Jesus Christ, salvation, church, sacraments, and the end times. Inbody also dives into provocative topics not usually treated in introductory texts -- creationism, the devil, miracles, the virgin birth, and more. The book\"s broad-ranging perspective, which intentionally defies labels, commends it to individuals and small groups from many church traditions. Quote boxes and illustrations drawn from popular culture make the text visually interesting and enjoyable to read. Inbody does not hide his own stance on issues but presents a full range of interpretations and openly points readers to other possibilities they can pursue. The Faith of the Christian Church offers just enough questions to provoke reflection and just enough answers to encourage readers to form their own grasp on the Christian faith.",
    "pageCount": 374,
    "printType": "BOOK",
    "genres": [ "Religion" ],
    "averageRating": 5,
    "ratingsCount": 1,
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "cHvF2SiBn-kC",
    "link": "http://books.google.com/books/about/The_Faith_of_the_Christian_Church.html?hl=&id=cHvF2SiBn-kC",
    "thumbnail": "http://books.google.com/books/content?id=cHvF2SiBn-kC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  {"title": "The Works of Francis Bacon, Lord Chancellor of England",
    "subtitle": "With a Life of the Author",
    "authors": [ "Francis Bacon", "Basil Montagu" ],
    "published": "1848",
    "printType": "BOOK",
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "hx0vWCeR1SEC",
    "link": "http://books.google.com/books/about/The_Works_of_Francis_Bacon_Lord_Chancell.html?hl=&id=hx0vWCeR1SEC",
    "thumbnail": "http://books.google.com/books/content?id=hx0vWCeR1SEC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {} },
  { "title": "The Man to See",
    "authors": [ "Evan Thomas" ],
    "publisher": "Simon and Schuster",
    "published": "1992-11-01",
    "description": "This bestselling biography of legendary trial lawyer Edward Bennett Williams is \"a skillful and lively portrait of a larger-than-life lawyer\" (Kirkus Reviews). Williams\" clients included Joe McCarthy, Frank Costello, Jimmy Hoffa, The Washington Post, and, just before Williams\" death in 1988, Michael Milken. 16 pages of photographs.",
    "pageCount": 592,
    "printType": "BOOK",
    "genres": [ "Biography & Autobiography" ],
    "maturityRating": "NOT_MATURE",
    "language": "en",
    "id": "1-U5x6Tmde0C",
    "link": "http://books.google.com/books/about/The_Man_to_See.html?hl=&id=1-U5x6Tmde0C",
    "thumbnail": "http://books.google.com/books/content?id=1-U5x6Tmde0C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    "images": {}
  }
]

module.exports = books